# Generated by Django 3.2.3 on 2021-09-02 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210829_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
